sdfdsf

diff --git a/.github/workflows/slack-notify-on-pr.yml b/.github/workflows/slack-notify-on-pr.yml
--- a/.github/workflows/slack-notify-on-pr.yml
+++ b/.github/workflows/slack-notify-on-pr.yml
@@ -7,34 +7,29 @@ on:
 
 jobs:
   conditional-job:
-    if: ${{ contains(join(fromJson(github.event.pull_request.labels | toJSON).name, ','), 'run-workflow') }}
+    if: contains(github.event.pull_request.labels.*.name, 'run-workflow') # Verifica si la etiqueta existe
     runs-on: ubuntu-latest
     steps:
-      - name: Setting env
+      - name: Setting env 
         id: set-env
         run: |
-          labels=$(jq -r '.pull_request.labels[].name' <<< "${{ toJSON(github.event) }}")
-          if [[ "$labels" == *"run-workflow"* ]]; then
-              echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
-          elif [[ "$labels" == *"run-something-else"* ]]; then
-              echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
+          if [[ "$(jq -r '.pull_request.labels[].name' <<< "$GITHUB_EVENT")" == *"run-workflow"* ]]; then
+            echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
+          elif [[ "$(jq -r '.pull_request.labels[].name' <<< "$GITHUB_EVENT")" == *"run-something-else"* ]]; then
+            echo "SLACK_WEBHOOK=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV
           else
-              echo "Error: Ninguna etiqueta coincide. SLACK_WEBHOOK no será configurado."
-              exit 1
+            echo "Error: Ninguna etiqueta coincide. SLACK_WEBHOOK no será configurado."
+            exit 1
           fi
+        env:
+          GITHUB_EVENT: ${{ toJson(github.event) }}
       - name: Send Slack Notification with curl
         run: |
-          if [[ -z "$SLACK_WEBHOOK" ]]; then
-              echo "Error: SLACK_WEBHOOK no está configurado."
-              exit 1
-          fi
-
           curl -X POST -H 'Content-type: application/json' \
-          --data "$(cat <<EOF
-          {
+          --data '{
             "blocks": [
               {
-                "type": "header",
+                "type": "header",git
                 "text": {
                   "type": "plain_text",
                   "text": "New PR Created :rocket:"
@@ -93,7 +88,5 @@ jobs:
                 ]
               }
             ]
-          }
-          EOF
-          )" \
+          }' \
           $SLACK_WEBHOOK
